package org.cricket.manager.probability;

/**
 * @author Baby's
 * The weight that will be generated by the probability function for each outcome depending upon the
 * probability factors. A weight is essentially the chances of that outcome coming true.
 * Weights are generated by the probabiityFunction and will be used by the probability engine to
 * create the probability distribution for a certain event. 
 */
public abstract class Weight {

}
